import tkinter as tk
def calculate():
    try:
        result = eval(entry.get())
        label.config(text=f"Result: {result}")
    except Exception as e:
        label.config(text=f"Error: {e}")
window = tk.Tk()
window.title("Calculator")
entry = tk.Entry(window, width=20)
entry.grid(row=0, column=0, columnspan=4)
button_7 = tk.Button(window, text="7", command=lambda: entry.insert(tk.END, "7"))
button_8 = tk.Button(window, text="8", command=lambda: entry.insert(tk.END, "8"))
button_9 = tk.Button(window, text="9", command=lambda: entry.insert(tk.END, "9"))
button_divide = tk.Button(window, text="/", command=lambda: entry.insert(tk.END, "/"))
button_7.grid(row=1, column=0)
button_8.grid(row=1, column=1)
button_9.grid(row=1, column=2)
button_divide.grid(row=1, column=3)
button_4 = tk.Button(window, text="4", command=lambda: entry.insert(tk.END, "4"))
button_5 = tk.Button(window, text="5", command=lambda: entry.insert(tk.END, "5"))
button_6 = tk.Button(window, text="6", command=lambda: entry.insert(tk.END, "6"))
button_multiply = tk.Button(window, text="*", command=lambda: entry.insert(tk.END, "*"))
button_4.grid(row=2, column=0)
button_5.grid(row=2, column=1)
button_6.grid(row=2, column=2)
button_multiply.grid(row=2, column=3)
button_1 = tk.Button(window, text="1", command=lambda: entry.insert(tk.END, "1"))
button_2 = tk.Button(window, text="2", command=lambda: entry.insert(tk.END, "2"))
button_3 = tk.Button(window, text="3", command=lambda: entry.insert(tk.END, "3"))
button_subtract = tk.Button(window, text="-", command=lambda: entry.insert(tk.END, "-"))
button_1.grid(row=3, column=0)
button_2.grid(row=3, column=1)
button_3.grid(row=3, column=2)
button_subtract.grid(row=3, column=3)
button_0 = tk.Button(window, text="0", command=lambda: entry.insert(tk.END, "0"))
button_decimal = tk.Button(window, text=".", command=lambda: entry.insert(tk.END, "."))
button_add = tk.Button(window, text="+", command=lambda: entry.insert(tk.END, "+"))
button_modulus = tk.Button(window, text="%", command=lambda: entry.insert(tk.END, "%"))
button_0.grid(row=4, column=0)
button_decimal.grid(row=4, column=1)
button_add.grid(row=4, column=2)
button_modulus.grid(row=4, column=3)
button_equals = tk.Button(window, text="=", command=calculate)
button_equals.grid(row=5, column=0, columnspan=4)
label = tk.Label(window, text="")
label.grid(row=6, column=0, columnspan=4)
window.mainloop()
